"""add created_by to hospitals

Revision ID: 3bea2fc959f0
Revises: b37526c11b42
Create Date: 2026-05-25 13:26:13.875689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bea2fc959f0'
down_revision: Union[str, None] = 'b37526c11b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('created_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'created_by')
    # ### end Alembic commands ###
