"""add updated_by to hospitals

Revision ID: 48f474eac5f7
Revises: 3bea2fc959f0
Create Date: 2026-05-25 13:36:55.676195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f474eac5f7'
down_revision: Union[str, None] = '3bea2fc959f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('updated_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'updated_by')
    # ### end Alembic commands ###
