"""add fk constraints to hospitals created_by updated_by

Revision ID: 868ec7f4e4f2
Revises: 48f474eac5f7
Create Date: 2026-05-25 14:38:16.250954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '868ec7f4e4f2'
down_revision: Union[str, None] = '48f474eac5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'hospitals', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'hospitals', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hospitals', type_='foreignkey')
    op.drop_constraint(None, 'hospitals', type_='foreignkey')
    # ### end Alembic commands ###
